name: Prisma DB Push
on: [push]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Push Schema to DB
        run: |
          npm install prisma@latest -g
          
          # Borramos el archivo de configuración si existe para evitar el error de sintaxis
          rm -f prisma.config.ts
          
          # Comando limpio: sin skip-generate y con accept-data-loss
          prisma db push --schema=./prisma/schema.prisma --accept-data-loss
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
