name: Prisma DB Push
on: [push]
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Push Schema to DB
        run: |
          # Instalamos prisma
          npm install prisma -g
          # Empujamos los cambios del esquema directamente a la DB
          # Usamos --accept-data-loss por seguridad de Prisma, aunque solo añadiremos índices
          prisma db push --schema=./prisma/schema.prisma
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
