name: 🌿 Seed Bible RV60

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install prisma @prisma/client xml2js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: npx prisma db push --force-reset  # Fuerza create tablas
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - run: |
          npx prisma generate
          node seed-node.js
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
