name: 🌿 Seed Bible RV60

on:
  workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install pg xml2js
      - name: Seed SQL Direct
        run: node seed-pg.js
        env:
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
